package com.exam.exam;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.json.bind.annotation.JsonRootElement
public class AppealAge_response implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean isoldenough;

	public AppealAge_response() {
	}

	public java.lang.Boolean getIsoldenough() {
		return this.isoldenough;
	}

	public void setIsoldenough(java.lang.Boolean isoldenough) {
		this.isoldenough = isoldenough;
	}

	public AppealAge_response(java.lang.Boolean isoldenough) {
		this.isoldenough = isoldenough;
	}

}