package com.exam.exam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AppealAge_response implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AppealAge_response() {
    }




}