package com.exam.exam;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class CourseRequirement implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean met;
	private java.lang.String alarm;

	public CourseRequirement() {
	}

	public java.lang.Boolean getMet() {
		return this.met;
	}

	public void setMet(java.lang.Boolean met) {
		this.met = met;
	}

	public java.lang.String getAlarm() {
		return this.alarm;
	}

	public void setAlarm(java.lang.String alarm) {
		this.alarm = alarm;
	}

	public CourseRequirement(java.lang.Boolean met, java.lang.String alarm) {
		this.met = met;
		this.alarm = alarm;
	}

}