package com.exam.exam;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class LastAppeal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean date;

	public LastAppeal() {
	}

	public java.lang.Boolean getDate() {
		return this.date;
	}

	public void setDate(java.lang.Boolean date) {
		this.date = date;
	}

	public LastAppeal(java.lang.Boolean date) {
		this.date = date;
	}

}