package com.exam.exam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class setByTeacher implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ExamCapacity")
	private java.lang.Integer capacity;
	public setByTeacher() {
	}

	public java.lang.Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(java.lang.Integer capacity) {
		this.capacity = capacity;
	}

	public setByTeacher(java.lang.Integer capacity) {
		this.capacity = capacity;
	}

}