package com.exam.exam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Student implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "GainedPoints")
	private java.lang.Integer points;

	public Student() {
	}

	public java.lang.Integer getPoints() {
		return this.points;
	}

	public void setPoints(java.lang.Integer points) {
		this.points = points;
	}

	public Student(java.lang.Integer points) {
		this.points = points;
	}

}