package com.exam.exam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StudentPoints implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public StudentPoints() {
    }




}