package com.exam.exam;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class StudentPoints implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer points;

	public StudentPoints() {
	}

	public java.lang.Integer getPoints() {
		return this.points;
	}

	public void setPoints(java.lang.Integer points) {
		this.points = points;
	}

	public StudentPoints(java.lang.Integer points) {
		this.points = points;
	}

}